name = "demo"
description = "demo"
long-description = """
Uses the generator (`../generator/`) to create stubbed subprograms for the interfacing package `digital_io/digital_io.ads`.
Provides Tcl commands to interface with the stubbed subprograms.

**NB** uses [libadalang2xml](https://github.com/simonjwright/libadalang2xml); build this separately, and place the executable `libadalang2xml` on the `PATH`.
"""
version = "2.1.0"

licenses = "CC0-1.0"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]

# Build the stub implementations.
[[actions]]
type = "pre-build"
command = ["make", "-C", "digital_io", "-f", "../../generator/Makefile.inc", "digital_io.adb"]

[[depends-on]]
scripted_testing = "*"

[[pins]]
scripted_testing = { path='..' }
